#Site
title: Chunxiao's Blog
subtitle:
description: To record anything that I wanna write
author: 

#Url
baseurl: /blog
githuburl: https://github.com/semicircles

#Serve
port: 3000

#Markdown
markdown: kramdown
highlighter: rouge

gems:
  - jemoji